name: Emscripten Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  Emscripten:
    runs-on: ubuntu-latest
    if: False
    
    steps:   
      # Install necessary packages
      - name: Install packages
        shell: sh
        run: sudo apt-get install git python3 cmake
        
      # Install emsdk
      - name: Install emsdk
        shell: sh
        run: |
          git clone https://github.com/emscripten-core/emsdk.git ~/emsdk
          ~/emsdk/emsdk install latest
          ~/emsdk/emsdk activate latest
          
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v3.3.0
        #### <---- FOR PRIVATE REPOS ----> ####
        #with:
        #  token: ${{ secrets.REPO_TOKEN }}
        #  submodules: recursive
          
      # Cache Submodules Handler (Reuse submodules from last run to speed up workflow)
      - name: Cache Submodules
        id: CacheStep
        uses: actions/cache@v3.2.5
        env:
          cache-name: cache-submodules-github.job
        with:
          path: ${{github.workspace}}/external
          key: github.job-build-${{ env.cache-name }}-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            github.job-build-${{ env.cache-name }}-
            github.job-build-
            github.job-

      # Install dependencies (Required libs to reduce compilation time)
      - name: Install dependencies
        shell: sh
        run: |
          sudo apt-get update
          #sudo apt-get install -y ...

      # Init Submodules if not cached
      - name: Init Submodules (If not cached)
        if: steps.CacheStep.outputs.cache-hit != 'true'
        shell: sh
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive

       # Enable Build Script to build executable
      - name: Enable Build Script
        shell: sh
        run: chmod +x ${{github.workspace}}/build.sh

      # Run Build Script (Init Submodules)
      - name: Run Build Script (Init Submodules)
        if: steps.CacheStep.outputs.cache-hit != 'true'
        shell: sh
        run: ${{github.workspace}}/build.sh --release --emscripten ~/emsdk

      # Run Build Script (Skip Init Submodules)
      - name: Run Build Script (Skip Init Submodules)
        if: steps.CacheStep.outputs.cache-hit == 'true'
        shell: sh
        run: ${{github.workspace}}/build.sh --release --skip-submodules --emscripten ~/emsdk

      # Execute tests defined by the CMake configuration.
      - name: Run CTest
        shell: sh
        working-directory: ${{github.workspace}}/build/emscripten/Release/
        run: ctest -C ${{env.BUILD_TYPE}}
